#!/bin/sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
OUTPUT_PATH="$REPO_ROOT/Termsy/Generated/WhatsNewGenerated.swift"
RAW_MESSAGES_PATH="$(mktemp)"
SOURCE_DESCRIPTION="last 20 commits"

trap 'rm -f "$RAW_MESSAGES_PATH"' EXIT

if PREVIOUS_TAG=$(git -C "$REPO_ROOT" describe --tags --abbrev=0 HEAD^ 2>/dev/null); then
	SOURCE_DESCRIPTION="$PREVIOUS_TAG..HEAD"
	git -C "$REPO_ROOT" log --format=%s "$PREVIOUS_TAG..HEAD" > "$RAW_MESSAGES_PATH"
else
	git -C "$REPO_ROOT" log --format=%s -n 20 HEAD > "$RAW_MESSAGES_PATH"
fi

escape_swift_string() {
	printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

mkdir -p "$(dirname "$OUTPUT_PATH")"

{
	cat <<EOF
//
//  WhatsNewGenerated.swift
//  Termsy
//
//  Generated by ci_scripts/generate_whats_new.sh.
//  Source: $SOURCE_DESCRIPTION
//
//  Do not edit by hand.
//

enum WhatsNewGenerated {
	static let current = WhatsNewContent(
		title: "What's New",
		summary: "A quick summary of the latest improvements in Termsy.",
		changes: [
EOF

	while IFS= read -r message || [ -n "$message" ]; do
		escaped_message=$(escape_swift_string "$message")
		printf '\t\t\t"%s",\n' "$escaped_message"
	done < "$RAW_MESSAGES_PATH"

	cat <<EOF
		]
	)
}
EOF
} > "$OUTPUT_PATH"

echo "Wrote $OUTPUT_PATH"
