#!/bin/sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
OUTPUT_PATH="$REPO_ROOT/Termsy/Generated/WhatsNewGenerated.swift"

source_description="last 20 commits"

collect_commit_messages() {
	if previous_tag=$(git -C "$REPO_ROOT" describe --tags --abbrev=0 HEAD^ 2>/dev/null); then
		source_description="$previous_tag..HEAD"
		git -C "$REPO_ROOT" log --no-merges --format=%s "$previous_tag..HEAD"
		return
	fi

	if bump_commit=$(git -C "$REPO_ROOT" log --grep='^[Bb]ump$' --format=%H -n 1 2>/dev/null); then
		source_description="$(git -C "$REPO_ROOT" rev-parse --short "$bump_commit")..HEAD"
		git -C "$REPO_ROOT" log --no-merges --format=%s "$bump_commit..HEAD"
		return
	fi

	git -C "$REPO_ROOT" log --no-merges --format=%s -n 20 HEAD
}

raw_messages_file="$(mktemp)"
trap 'rm -f "$raw_messages_file"' EXIT

collect_commit_messages > "$raw_messages_file"

if [ ! -s "$raw_messages_file" ]; then
	source_description="last 20 commits"
	git -C "$REPO_ROOT" log --no-merges --format=%s -n 20 HEAD > "$raw_messages_file"
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"

python3 - "$raw_messages_file" "$OUTPUT_PATH" "$source_description" <<'PY'
from pathlib import Path
import sys

messages_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])
source_description = sys.argv[3]

blocked_exact = {
    "wip",
    "bump",
    "fixes",
    "first",
    "initial commit",
    "eat pray love",
}
blocked_prefixes = (
    "merge ",
    "docs:",
    "doc:",
    "chore:",
    "ci:",
    "test:",
    "tests:",
    "release:",
    "release ",
    "version ",
)


def include_message(message: str) -> bool:
    normalized = message.strip()
    if not normalized:
        return False

    lowered = normalized.lower()
    if lowered in blocked_exact:
        return False
    if lowered.startswith(blocked_prefixes):
        return False
    return True


def normalize_message(message: str) -> str:
    normalized = " ".join(message.strip().split())
    if not normalized:
        return normalized

    normalized = normalized[0].upper() + normalized[1:]
    if normalized[-1] not in ".!?":
        normalized += "."
    return normalized


def swift_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("\n", "\\n")
    return f'"{escaped}"'


seen = set()
bullets: list[str] = []
for raw_message in messages_path.read_text().splitlines():
    if not include_message(raw_message):
        continue

    bullet = normalize_message(raw_message)
    key = bullet.casefold()
    if key in seen:
        continue

    seen.add(key)
    bullets.append(bullet)
    if len(bullets) == 5:
        break

if not bullets:
    bullets = ["Bug fixes and improvements."]

bullet_lines = "\n".join(f"\t\t\t{swift_string(bullet)}," for bullet in bullets)
if bullet_lines.endswith(","):
    bullet_lines = bullet_lines[:-1]

content = f"""//
//  WhatsNewGenerated.swift
//  Termsy
//
//  Generated by ci_scripts/generate_whats_new.sh.
//  Source: {source_description}
//
//  Do not edit by hand.
//

enum WhatsNewGenerated {{
\tstatic let current = WhatsNewContent(
\t\ttitle: {swift_string("What's New")},
\t\tsummary: {swift_string("A quick summary of the latest improvements in Termsy.")},
\t\tchanges: [
{bullet_lines}
\t\t]
\t)
}}
"""

output_path.write_text(content)
PY

echo "Wrote $OUTPUT_PATH"
